--ALTER TABLE XOSERVE.TABLE_REPOSITORY ADD (SLICE_PERIOD NVARCHAR(2))

UPDATE XOSERVE.TEST_TABLE_0 SET DIREPL_STATUS = 'W' WHERE  DIREPL_STATUS = 'C';
UPDATE XOSERVE.TEST_TABLE_1 SET DIREPL_STATUS = 'W' WHERE  DIREPL_STATUS = 'C';
UPDATE XOSERVE.TEST_TABLE_2 SET DIREPL_STATUS = 'W' WHERE  DIREPL_STATUS = 'C';
UPDATE XOSERVE.TEST_TABLE_3 SET DIREPL_STATUS = 'W' WHERE  DIREPL_STATUS = 'C';
UPDATE XOSERVE.TEST_TABLE_4 SET DIREPL_STATUS = 'W' WHERE  DIREPL_STATUS = 'C';
UPDATE XOSERVE.TEST_TABLE_5 SET DIREPL_STATUS = 'W' WHERE  DIREPL_STATUS = 'C';
UPDATE XOSERVE.TEST_TABLE_6 SET DIREPL_STATUS = 'W' WHERE  DIREPL_STATUS = 'C';
UPDATE XOSERVE.TEST_TABLE_7 SET DIREPL_STATUS = 'W' WHERE  DIREPL_STATUS = 'C';
UPDATE XOSERVE.TEST_TABLE_8 SET DIREPL_STATUS = 'W' WHERE  DIREPL_STATUS = 'C';
UPDATE XOSERVE.TEST_TABLE_9 SET DIREPL_STATUS = 'W' WHERE  DIREPL_STATUS = 'C';
