# First 3 lines generated by di-pyoperator - DO NOT CHANGE (Deleted again when uploaded.)
from utils.mock_di_api import mock_api
api = mock_api(__file__)

import logging
import io

# catching logger messages for separate output
log_stream = io.StringIO()
sh = logging.StreamHandler(stream=log_stream)
sh.setFormatter(logging.Formatter('\"%(asctime)s\" | %(name)s | \"%(message)s\"', datefmt='%H:%M:%S'))
api.logger.addHandler(sh)

def process(msg):

    att = dict(msg.attributes)
    att['operator'] = 'selectdata'
    table = att['schema_name'] + '.' + att['table_name']

    # Create SQL-statement
    sql = 'SELECT * FROM {table} WHERE \"DIREPL_PID\" = \'{pid}\' '.\
        format(table=table,pid= att['pid'])
    api.logger.info('{}'.format(sql))

    # Send to data-outport
    api.send(outports[1]['name'], api.Message(attributes=att,body = sql))

    # Send to log-outport
    api.send(outports[0]['name'], log_stream.getvalue() )
    log_stream.seek(0)
    log_stream.truncate()


inports = [{'name': 'trigger', 'type': 'message.table', "description": "Input data"}]
outports = [{'name': 'log', 'type': 'string', "description": "Logging data"}, \
            {'name': 'msg', 'type': 'message', "description": "message with sql statement"}]

api.set_port_callback(inports[0]['name'], process)
